/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoardRouteImport } from './routes/board'
import { Route as DraftRouteImport } from './routes/draft'
import { Route as InstructionsRouteImport } from './routes/instructions'
import { Route as LeagueRouteImport } from './routes/league'
import { Route as LeaguesRouteImport } from './routes/leagues'
import { Route as MatchupRouteImport } from './routes/matchup'
import { Route as PlayersRouteImport } from './routes/players'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as StandingsRouteImport } from './routes/standings'
import { Route as TeamRouteImport } from './routes/team'
import { Route as LeaguesCodeRouteImport } from './routes/leagues.$code'
import { Route as PlayerHandleRouteImport } from './routes/player.$handle'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftRoute = DraftRouteImport.update({
  id: '/draft',
  path: '/draft',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructionsRoute = InstructionsRouteImport.update({
  id: '/instructions',
  path: '/instructions',
  getParentRoute: () => rootRouteImport,
} as any)
const LeagueRoute = LeagueRouteImport.update({
  id: '/league',
  path: '/league',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaguesRoute = LeaguesRouteImport.update({
  id: '/leagues',
  path: '/leagues',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchupRoute = MatchupRouteImport.update({
  id: '/matchup',
  path: '/matchup',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersRoute = PlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const StandingsRoute = StandingsRouteImport.update({
  id: '/standings',
  path: '/standings',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaguesCodeRoute = LeaguesCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => LeaguesRoute,
} as any)
const PlayerHandleRoute = PlayerHandleRouteImport.update({
  id: '/player/$handle',
  path: '/player/$handle',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/board': typeof BoardRoute
  '/draft': typeof DraftRoute
  '/instructions': typeof InstructionsRoute
  '/league': typeof LeagueRoute
  '/leagues': typeof LeaguesRouteWithChildren
  '/matchup': typeof MatchupRoute
  '/players': typeof PlayersRoute
  '/rules': typeof RulesRoute
  '/standings': typeof StandingsRoute
  '/team': typeof TeamRoute
  '/leagues/$code': typeof LeaguesCodeRoute
  '/player/$handle': typeof PlayerHandleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/board': typeof BoardRoute
  '/draft': typeof DraftRoute
  '/instructions': typeof InstructionsRoute
  '/league': typeof LeagueRoute
  '/leagues': typeof LeaguesRouteWithChildren
  '/matchup': typeof MatchupRoute
  '/players': typeof PlayersRoute
  '/rules': typeof RulesRoute
  '/standings': typeof StandingsRoute
  '/team': typeof TeamRoute
  '/leagues/$code': typeof LeaguesCodeRoute
  '/player/$handle': typeof PlayerHandleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/board': typeof BoardRoute
  '/draft': typeof DraftRoute
  '/instructions': typeof InstructionsRoute
  '/league': typeof LeagueRoute
  '/leagues': typeof LeaguesRouteWithChildren
  '/matchup': typeof MatchupRoute
  '/players': typeof PlayersRoute
  '/rules': typeof RulesRoute
  '/standings': typeof StandingsRoute
  '/team': typeof TeamRoute
  '/leagues/$code': typeof LeaguesCodeRoute
  '/player/$handle': typeof PlayerHandleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/board'
    | '/draft'
    | '/instructions'
    | '/league'
    | '/leagues'
    | '/matchup'
    | '/players'
    | '/rules'
    | '/standings'
    | '/team'
    | '/leagues/$code'
    | '/player/$handle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/board'
    | '/draft'
    | '/instructions'
    | '/league'
    | '/leagues'
    | '/matchup'
    | '/players'
    | '/rules'
    | '/standings'
    | '/team'
    | '/leagues/$code'
    | '/player/$handle'
  id:
    | '__root__'
    | '/'
    | '/board'
    | '/draft'
    | '/instructions'
    | '/league'
    | '/leagues'
    | '/matchup'
    | '/players'
    | '/rules'
    | '/standings'
    | '/team'
    | '/leagues/$code'
    | '/player/$handle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoardRoute: typeof BoardRoute
  DraftRoute: typeof DraftRoute
  InstructionsRoute: typeof InstructionsRoute
  LeagueRoute: typeof LeagueRoute
  LeaguesRoute: typeof LeaguesRouteWithChildren
  MatchupRoute: typeof MatchupRoute
  PlayersRoute: typeof PlayersRoute
  RulesRoute: typeof RulesRoute
  StandingsRoute: typeof StandingsRoute
  TeamRoute: typeof TeamRoute
  PlayerHandleRoute: typeof PlayerHandleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/draft': {
      id: '/draft'
      path: '/draft'
      fullPath: '/draft'
      preLoaderRoute: typeof DraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructions': {
      id: '/instructions'
      path: '/instructions'
      fullPath: '/instructions'
      preLoaderRoute: typeof InstructionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/league': {
      id: '/league'
      path: '/league'
      fullPath: '/league'
      preLoaderRoute: typeof LeagueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leagues': {
      id: '/leagues'
      path: '/leagues'
      fullPath: '/leagues'
      preLoaderRoute: typeof LeaguesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matchup': {
      id: '/matchup'
      path: '/matchup'
      fullPath: '/matchup'
      preLoaderRoute: typeof MatchupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players': {
      id: '/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standings': {
      id: '/standings'
      path: '/standings'
      fullPath: '/standings'
      preLoaderRoute: typeof StandingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leagues/$code': {
      id: '/leagues/$code'
      path: '/$code'
      fullPath: '/leagues/$code'
      preLoaderRoute: typeof LeaguesCodeRouteImport
      parentRoute: typeof LeaguesRoute
    }
    '/player/$handle': {
      id: '/player/$handle'
      path: '/player/$handle'
      fullPath: '/player/$handle'
      preLoaderRoute: typeof PlayerHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LeaguesRouteChildren {
  LeaguesCodeRoute: typeof LeaguesCodeRoute
}

const LeaguesRouteChildren: LeaguesRouteChildren = {
  LeaguesCodeRoute: LeaguesCodeRoute,
}

const LeaguesRouteWithChildren =
  LeaguesRoute._addFileChildren(LeaguesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoardRoute: BoardRoute,
  DraftRoute: DraftRoute,
  InstructionsRoute: InstructionsRoute,
  LeagueRoute: LeagueRoute,
  LeaguesRoute: LeaguesRouteWithChildren,
  MatchupRoute: MatchupRoute,
  PlayersRoute: PlayersRoute,
  RulesRoute: RulesRoute,
  StandingsRoute: StandingsRoute,
  TeamRoute: TeamRoute,
  PlayerHandleRoute: PlayerHandleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
